language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: zenial

install:
  - pip install -r requirements.txt

script:
  - pytest
  - isort -c
  # TODO: Add flake8 validation
  - docker build -t vaahtokarkki/hue-geofencing .

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
