language: python

services:
  - docker

matrix:
  include:
    - python: 3.7
      dist: zenial

install:
  - pip install -r requirements.txt

script:
  - pytest
  - flake8
  - isort -c

after_script:
  - codecov --token=CODECOV_TOKEN

deploy:
  provider: script
  script: bash deploy.sh
  on:
    branch: master
