language: python

services:
  - docker

python:
  - "3.7"

install:
  - pip install -r requirements.txt

script:
  - pytest
  - isort -c
  # TODO: Add flake8 validation
  - docker build -t vaahtokarkki/hue-geofencing