name: hue-geofencing

on:
  push:
    branches:
      - master

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        flake8 . --count --show-source --statistics
        isort -c
    - name: Test with pytest
      run: |
        pytest

  build-docker-images:
    runs-on: ubuntu-latest
    needs: build-test-push
    steps:
    - uses: actions/checkout@v1
    - name: Create empty env file to pass build
      run: touch .env
    - name: Build the docker-compose stack
      run: docker-compose build
    - name: Tag latest
      run: docker tag vaahtokarkki/hue-geofencing:amd64 vaahtokarkki/hue-geofencing:latest
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push tagged images
      run: docker-compose push
    - name: Push latest
      run: docker push vaahtokarkki/hue-geofencing:latest
  
